[Containerapp] `az containerapp sessionpool update`: Fix updating registry credentials with `--registry-username` and `--registry-password` when existing registry credentials are empty (#8483)
* fix

* fix issue: NoneType error

* add history

* update test

* fix style: src/containerapp/azext_containerapp/_utils.py:109:37: E1123: Unexpected keyword argument 'resource' in method call (unexpected-keyword-arg)

* remove unused function

* add more guidance

---------

Co-authored-by: xinyu pang <xinyupang@microsoft.com>