{confcom} Fix lint
Fix the following (likely newly introduced) lints:

```
ERROR: ************* Module azext_confcom._params
src/confcom/azext_confcom/_params.py:54:17: W4904: Using deprecated class FileType of module argparse (deprecated-class)
src/confcom/azext_confcom/_params.py:73:17: W4904: Using deprecated class FileType of module argparse (deprecated-class)
src/confcom/azext_confcom/_params.py:558:17: W4904: Using deprecated class FileType of module argparse (deprecated-class)
************* Module azext_confcom.container
src/confcom/azext_confcom/container.py:577:4: W0102: Dangerous default value dict() (builtins.dict) as argument (dangerous-default-value)
```

Touches some non-related code, but I think the changes are good.

Assisted-by: GitHub Copilot:claude-opus-4.7 copilot-review
Signed-off-by: Tingmao Wang <m@maowtm.org>